---
apiVersion: v1
kind: ConfigMap
metadata:
  name: course-service-config
data:
  PORT: "3004"
  COURSE_GRPC_PORT: "5004"
  MONGODB_URL_COURSE: "mongodb+srv://jacksoncheriyan05:MongoDBPassword@cluster0.oh2lv.mongodb.net/CourseDB"
  BUCKET_NAME: "dowhilelearn"
  AWS_REGION: "eu-north-1"
  LOG_RETENTION_DAYS: "7d"
  COURSE_UPDATE: "course.update"
  COURSE_ROLLBACK: "course-service.rollback"
  COURSE_RESPONSE: "course.response"
  COURSE_ROLLBACK_COMPLETED: "rollback-completed"
  COURSE_SERVICE_GROUP: "course-service-group"
---
apiVersion: v1
kind: Secret
metadata:
  name: course-service-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "QUtJQTRaUFpVNUxMR09SN0xLREM="
  AWS_SECRET_ACCESS_KEY: "OWk3Rm1GRGtFblNzSzVJeFRsRE5wdUFKSDJhbVo1dlNCMVFVcjRRdw=="
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: course-service
 labels:
   app: course-service
spec:
 replicas: 2
 selector:
   matchLabels:
     app: course-service
 template:
   metadata:
     labels:
       app: course-service
   spec:
     hostAliases:
     - ip: "172.17.0.1"  # Docker host IP
       hostnames:
       - "education-kafka"
     containers:
     - name: course-service
       image: course-service:latest
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 5004
         name: grpc
       - containerPort: 3004
         name: kafka
       envFrom:
       - configMapRef:
           name: course-service-config
       - secretRef:
           name: course-service-secrets
       resources:
         limits:
           memory: "512Mi"
           cpu: "500m"
         requests:
           memory: "256Mi"
           cpu: "250m"
       readinessProbe:
         tcpSocket:
           port: grpc
         initialDelaySeconds: 5
         periodSeconds: 10
       livenessProbe:
         tcpSocket:
           port: grpc
         initialDelaySeconds: 15
         periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  type: ClusterIP
  ports:
  - port: 5004
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: 3004
    targetPort: kafka
    protocol: TCP
    name: kafka
  selector:
    app: course-service